export const GET_COMPANIES = `GET_COMPANIES`;
export const COMPANIES_RECEIVED = `COMPANIES_RECEIVED`;
export const COMPANIES_FAILED = `COMPANIES_FAILED`;

export const GET_BANKS = `GET_BANKS`;
export const BANKS_RECEIVED = `BANKS_RECEIVED`;
export const BANKS_FAILED = `BANKS_FAILED`;

export const ADD_COMPANY = `ADD_COMPANY`;
export const ADD_COMPANY_SUCCESS = `ADD_COMPANY_SUCCESS`;
export const ADD_COMPANY_FAILED = `ADD_COMPANY_FAILED`;

export const ADD_BANK = `ADD_BANK`;
export const ADD_BANK_SUCCESS = `ADD_BANK_SUCCESS`;
export const ADD_BANK_FAILED = `ADD_BANK_FAILED`;


export const DELETE_COMPANY = `DELETE_COMPANY`;
export const DELETE_COMPANY_SUCCESS = `DELETE_COMPANY_SUCCESS`;
export const DELETE_COMPANY_FAILED = `DELETE_COMPANY_FAILED`;

export const DELETE_BANK  = `DELETE_BANK `;
export const DELETE_BANK_SUCCESS = `DELETE_BANK_SUCCESS`;
export const DELETE_BANK_FAILED = `DELETE_BANK_FAILED`;

export const GET_COMPANY = `GET_COMPANY`;
export const COMPANY_RECEIVED = `COMPANY_RECEIVED`;
export const COMPANY_FAILED = `COMPANY_FAILED`;

export const UPDATE_COMPANY = `UPDATE_COMPANY`;
export const UPDATE_COMPANY_SUCCESS = `UPDATE_COMPANY_SUCCESS`;
export const UPDATE_COMPANY_FAILED = `UPDATE_COMPANY_FAILED`;

export const UPDATE_BANK = `UPDATE_BANK`;
export const UPDATE_BANK_SUCCESS = `UPDATE_BANK_SUCCESS`;
export const UPDATE_BANK_FAILED = `UPDATE_BANKY_FAILED`;

export const SIGN_IN = `SIGN_IN`;
export const SIGN_IN_SUCCESS = `SIGN_IN_SUCCESS`;
export const SIGN_IN_FAILED = `SIGN_IN_FAILED`;

export const SIGN_OUT = `SIGN_OUT`;

export const SET_CURRENT_USER = `SET_CURRENT_USER`;
